import QtQuick
import Quickshell
import Quickshell.Io
import qs.Commons

Item {
  id: root

  property var shell: null
  property var manifest: null
  property var pluginRegistry: null

  readonly property string pluginId: "io.github.inde3d100.homearchy"
  readonly property string home: Quickshell.env("HOME") || "/tmp"
  readonly property string pluginDir: {
    var url = String(Qt.resolvedUrl("."))
    if (url.indexOf("file://") === 0) url = url.slice(7)
    if (url.length > 1 && url.charAt(url.length - 1) === "/") url = url.slice(0, url.length - 1)
    return url
  }
  readonly property string enginePath: pluginDir + "/bin/homearchy"
  readonly property string stateDir: home + "/.local/state/homearchy"
  readonly property string configPath: stateDir + "/plugin.toml"

  property string engineState: "starting"
  property string mode: "idle"
  property string version: ""
  property string error: ""
  property bool engineEnabled: true
  property bool ready: false
  property bool stopping: false
  property bool restartRequested: false
  property int restartAttempt: 0

  function colorHex(value) {
    var text = String(value || "")
    if (/^#[0-9a-fA-F]{8}$/.test(text) && text.slice(1, 3).toLowerCase() === "ff")
      return "#" + text.slice(3)
    return text
  }

  function generatedConfig() {
    var surface = colorHex(Color.background)
    var accent = colorHex(Color.accent)
    var text = colorHex(Color.foreground)
    return "# Generated by the Homearchy Omarchy plugin.\n" +
      "[theme.light]\n" +
      "surface = \"" + surface + "\"\n" +
      "accent = \"" + accent + "\"\n" +
      "accent_alt = \"" + text + "\"\n" +
      "on_accent_alt = \"" + surface + "\"\n" +
      "text = \"" + text + "\"\n\n" +
      "[theme.dark]\n" +
      "surface = \"" + surface + "\"\n" +
      "accent = \"" + accent + "\"\n" +
      "accent_alt = \"" + text + "\"\n" +
      "on_accent_alt = \"" + surface + "\"\n" +
      "text = \"" + text + "\"\n\n" +
      "[hotkeys]\n" +
      "\"Super+Shift+H\" = \"hints --action left_click\"\n" +
      "\"Super+Shift+U\" = \"hints --search --action left_click\"\n" +
      "\"Super+Shift+J\" = \"grid --action left_click\"\n" +
      "\"Super+Shift+R\" = \"recursive_grid --action left_click\"\n" +
      "\"Super+Shift+Z\" = \"scroll\"\n" +
      "\"Super+Shift+I\" = \"monitor_select\"\n" +
      "\"Super+Shift+Escape\" = \"idle\"\n\n" +
      "[logging]\n" +
      "disable_file_logging = false\n" +
      "log_level = \"info\"\n\n" +
      "[monitor_select]\n" +
      "enabled = true\n\n" +
      "[grid.hotkeys]\n" +
      "\"Space\" = [\"action left_click\", \"idle\"]\n" +
      "\"Return\" = [\"action right_click\", \"idle\"]\n\n" +
      "[recursive_grid.hotkeys]\n" +
      "\"Space\" = [\"action left_click\", \"idle\"]\n" +
      "\"Return\" = [\"action right_click\", \"idle\"]\n\n" +
      "[scroll]\n" +
      "invert_scroll = true\n"
  }

  function writeConfig() {
    configFile.setText(generatedConfig())
  }

  function startEngine() {
    if (stopping || engineProcess.running) return
    engineState = "starting"
    ready = false
    error = ""
    engineProcess.command = [enginePath, "--config", configPath, "launch"]
    engineProcess.running = true
    statusTimer.restart()
  }

  function requestRestart() {
    if (stopping) return "stopping"
    restartRequested = true
    if (engineProcess.running) engineProcess.running = false
    else startEngine()
    return "restarting"
  }

  function runMode(arguments) {
    if (!ready) return "not-ready"
    if (actionProcess.running) return "busy"
    actionProcess.command = [enginePath].concat(arguments)
    actionProcess.running = true
    return "ok"
  }

  function snapshot() {
    return {
      schema_version: 1,
      state: engineState,
      mode: mode,
      version: version,
      enabled: engineEnabled,
      ready: ready,
      error: error
    }
  }

  function applyStatus(raw) {
    try {
      var status = JSON.parse(String(raw || ""))
      if (Number(status.schema_version) !== 1) throw new Error("unsupported status schema")
      engineState = String(status.state || "unknown")
      mode = String(status.mode || "idle")
      version = String(status.version || "")
      engineEnabled = status.enabled !== false
      ready = engineState === "running"
      error = ""
      restartAttempt = 0
    } catch (statusError) {
      ready = false
      error = String(statusError)
    }
  }

  Component.onCompleted: {
    setupProcess.command = ["mkdir", "-p", stateDir]
    setupProcess.running = true
  }

  Component.onDestruction: {
    stopping = true
    statusTimer.stop()
    restartTimer.stop()
    if (actionProcess.running) actionProcess.running = false
    if (engineProcess.running) engineProcess.running = false
  }

  Connections {
    target: Color
    function onBackgroundChanged() { configWriteTimer.restart() }
    function onForegroundChanged() { configWriteTimer.restart() }
    function onAccentChanged() { configWriteTimer.restart() }
  }

  FileView {
    id: configFile
    path: root.configPath
    atomicWrites: true
    printErrors: true
  }

  Process {
    id: setupProcess
    running: false
    onExited: function(exitCode) {
      if (exitCode !== 0) {
        root.engineState = "error"
        root.error = "could not create " + root.stateDir
        return
      }
      root.writeConfig()
      Qt.callLater(root.startEngine)
    }
  }

  Process {
    id: engineProcess
    running: false
    onRunningChanged: {
      if (running) {
        root.engineState = "starting"
        root.error = ""
      }
    }
    onExited: function(exitCode) {
      root.ready = false
      root.mode = "idle"
      if (root.stopping) return
      if (root.restartRequested) {
        root.restartRequested = false
        Qt.callLater(root.startEngine)
        return
      }
      root.engineState = "error"
      root.error = "engine exited with code " + exitCode
      root.restartAttempt += 1
      restartTimer.interval = Math.min(30000, 1000 * Math.pow(2, root.restartAttempt - 1))
      restartTimer.restart()
    }
  }

  Process {
    id: statusProcess
    running: false
    command: [root.enginePath, "status", "--json"]
    stdout: StdioCollector { id: statusOutput; waitForEnd: true }
    onExited: function(exitCode) {
      if (exitCode === 0) root.applyStatus(statusOutput.text)
      else if (root.engineState !== "error") root.ready = false
    }
  }

  Process {
    id: actionProcess
    running: false
  }

  Timer {
    id: statusTimer
    interval: 2000
    repeat: true
    running: false
    triggeredOnStart: true
    onTriggered: if (!statusProcess.running) statusProcess.running = true
  }

  Timer {
    id: restartTimer
    interval: 1000
    repeat: false
    onTriggered: root.startEngine()
  }

  Timer {
    id: configWriteTimer
    interval: 200
    repeat: false
    onTriggered: root.writeConfig()
  }

  IpcHandler {
    target: root.pluginId

    function status(): string { return JSON.stringify(root.snapshot()) }
    function restart(): string { return root.requestRestart() }
    function hints(): string { return root.runMode(["hints", "--action", "left_click"]) }
    function search(): string { return root.runMode(["hints", "--search", "--action", "left_click"]) }
    function grid(): string { return root.runMode(["grid", "--action", "left_click"]) }
    function recursiveGrid(): string { return root.runMode(["recursive_grid", "--action", "left_click"]) }
    function scroll(): string { return root.runMode(["scroll"]) }
    function monitorSelect(): string { return root.runMode(["monitor_select"]) }
  }
}
